# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-18 19:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 13, 21, 705000, tzinfo=utc), verbose_name='Submetido')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 13, 21, 705499, tzinfo=utc), verbose_name='Publicado')),
                ('data_ultima_modificacao', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 13, 21, 705499, tzinfo=utc), verbose_name='Modificado')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(default='media/none.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Luiz Fernando Reinos\\Documents\\Projetos\\CABoard\\static'), upload_to='media/upload_user')),
                ('link_site', models.CharField(blank=True, max_length=1000)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 13, 21, 706000, tzinfo=utc), verbose_name='Submetido')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 13, 21, 706000, tzinfo=utc), verbose_name='Publicado')),
                ('data_ultima_modificacao', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 13, 21, 706000, tzinfo=utc), verbose_name='Modificado')),
                ('ordem', models.IntegerField(blank=True, verbose_name='Ordem')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
        ),
    ]
