# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-18 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaprojeto',
            name='data_ultima_modificacao',
        ),
        migrations.RemoveField(
            model_name='mediaprojeto',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='mediaprojeto',
            name='publicado',
        ),
        migrations.AlterField(
            model_name='board',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 25, 45, 429306, tzinfo=utc), verbose_name='Submetido'),
        ),
        migrations.AlterField(
            model_name='board',
            name='data_ultima_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 25, 45, 429306, tzinfo=utc), verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 25, 45, 429306, tzinfo=utc), verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='mediaprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 25, 45, 430306, tzinfo=utc), verbose_name='Submetido'),
        ),
    ]
