# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180518_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaprojeto',
            name='significado',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 14, 56, 739648, tzinfo=utc), verbose_name='Submetido'),
        ),
        migrations.AlterField(
            model_name='board',
            name='data_ultima_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 14, 56, 739648, tzinfo=utc), verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 14, 56, 739648, tzinfo=utc), verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='mediaprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 14, 56, 740649, tzinfo=utc), verbose_name='Submetido'),
        ),
        migrations.AlterField(
            model_name='mediaprojeto',
            name='ordem',
            field=models.IntegerField(default=-1, verbose_name='Ordem'),
        ),
    ]
