# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180612_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 16, 41, 838224, tzinfo=utc), verbose_name='Submetido'),
        ),
        migrations.AlterField(
            model_name='board',
            name='data_ultima_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 16, 41, 838224, tzinfo=utc), verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 16, 41, 838224, tzinfo=utc), verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='mediaprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 16, 41, 839224, tzinfo=utc), verbose_name='Submetido'),
        ),
        migrations.AlterField(
            model_name='mediaprojeto',
            name='significado',
            field=models.CharField(max_length=255),
        ),
    ]
